export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
export const FETCH_RENTALS_FAILURE = 'FETCH_RENTALS_FAILURE';
export const FETCH_RENTAL_BY_ID_SUCCESS = 'FETCH_RENTAL_BY_ID_SUCCESS';
export const FETCH_RENTAL_BY_ID_INIT = 'FETCH_RENTAL_BY_ID_INIT';

export const FETCH_USER_BOOKINGS_INIT = 'FETCH_USER_BOOKINGS_INIT';
export const FETCH_USER_BOOKINGS_SUCCESS = 'FETCH_USER_BOOKINGS_SUCCESS';
export const FETCH_USER_BOOKINGS_FAILURE = 'FETCH_USER_BOOKINGS_FAILURE';

export const FETCH_REVIEWS_FOR_RENTAL_INIT = 'FETCH_REVIEWS_FOR_RENTAL_INIT';
export const FETCH_REVIEWS_FOR_RENTAL_SUCCESS = 'FETCH_REVIEWS_FOR_RENTAL_SUCCESS';
export const FETCH_REVIEWS_FOR_RENTAL_FAILURE = 'FETCH_REVIEWS_FOR_RENTAL_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';